export const SET_SEARCH = 'SET_SEARCH'
export const SET_LOADING = 'SET_LOADING'
export const SET_RESULTS = 'SET_RESULTS'
export const ADD_RESULTS = 'ADD_RESULTS'
export const SELECT_MOVIE = 'SELECT_MOVIE'
